# Generated by Django 3.1.3 on 2020-12-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BunnyRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('no_arg_return', models.CharField(max_length=100)),
                ('arg_return', models.CharField(max_length=100)),
            ],
        ),
    ]
